### PR TITLE
Use DBItest for testing

### PR DESCRIPTION
**Pull request by krlmlr**
Currently calls `test_all()`: this may or may not be desired.

### CODE REVIEW

**Comment by krlmlr** [comment]
Includes infrastructure, fixes a minor bug, removes tests now covered by DBItest.

**Comment by krlmlr** [comment]
@hadley: Okay to merge?

**Comment by hadley** [comment]
Go for it

**Comment by krlmlr** [comment]
Travis-testing the pull request fails, but the branch itself tests correctly. Will fix errors in master.

**Pull request merged**
